LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"

SEG_TOKEN_INDEX = -300
DEFAULT_SEG_TOKEN = "<seg>"

DEPTH_TOKEN_INDEX = -400
DEFAULT_DEPTH_TOKEN = "<depth>"
